config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root to: 'static_pages#home'
	get 'about', to: 'static_pages#about'
	get 'contact_us', to: 'static_pages#contact_us'
	resources :bookings
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	phony_normalize :phone, default_country_code: 'PL'
  
	belongs_to :user

	enum status: [ :pending, :confirmed ]

	validates :phone, phony_plausible: true
	validates :user_id, presence: true
	validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [ :regular_permissions, :admin_permissions ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	before_action :authenticate_user!

	def index
		if current_user.role = "admin_permissions"
			@bookings = Booking.all
		else
			@bookings = current_user.bookings.all
		end
	end

	def create
		date = params[:booking_from]
		date = DateTime.parse(date)
		phone = params[:phone]
		@booking = current_user.bookings.new(booking_from: date, booking_to: date, phone: phone, name: params[:name])
		# if @booking.booking_from > @booking.booking_to
		# 	redirect_to new_booking_path, flash: { danger: "Invalid dates"}
		# elsif @booking.phone.length > 9 || @booking.phone.length < 9
		# 	redirect_to new_booking_path, flash: { danger: "Invalid phone number"}
		# elsif @booking.name.empty?
		# 	redirect_to
		if @booking.save
			redirect_to bookings_path, flash: { success: "booking saved"}
		else
			redirect_to new_booking_path, flash: { danger: "the form contains errors"} 
			
		end
	end

	def update

		updated_name = params[:name]
		updated_date = params[:booking_from]
		updated_phone = params[:phone]

		@update = Booking.find(params[:id])

		@booking = Booking.update(booking_from: updated_date, name: updated_name, phone: updated_phone)

		redirect_to bookings_path



		# date = params[:booking_from]
		# date = DateTime.parse(date)
		# phone = params[:phone]
		# @booking = current_user.bookings.update(booking_from: date, booking_to: date, phone: phone, name: params[:name])
		
		# @booking = Booking.find_by(params[:id])
		# @booking.update(params[:bookings])

	end

	def destroy
		Booking.find(params[:id]).destroy
		redirect_to bookings_path
	end

	def show
	end

	private

	# def current_id


	# def errors

	# 	if @booking.booking_from > @booking.booking_to
			
	# 	elsif @booking.phone.length > 9 || @booking.phone.length < 9
	# 		redirect_to new_booking_path, flash: { danger: "Invalid phone number"}
	# end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def about
	end

	def contact_us
	end

	def gallery
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.slim
.container
	h1 all the items

	- flash.each do |type, message|
		.notification class="is-#{type}"
			= message 

	ul
		li
			- @bookings.each_with_index do |f, idx|
				h1 Booking number #{idx + 1}
				= f.id
				= f.user_id
				= f.booking_from

				= link_to "Edit", booking_path(f.id), method: :patch, class: "button"
			
				= link_to "Delete", booking_path(f.id), method: :delete, class: "button is-primary"

app/views/bookings/new.slim
.container
	- flash.each do |type, message|
		.notification class="is-#{type}"
			= message 
			
	h1 welcome to bookings
	= form_with url: bookings_path do |form|
		= form.hidden_field :status, value: "1"
		= form.label :name, "please enter your name"
		= form.text_field :name, class: "input"
		= form.label :date, "Please select a date"
		= form.text_field :booking_from, class: "datepicker", type: "date", id: "datepicker"
		= form.label :phone, "Phone number"
		= form.text_field :phone, class: "input"
		= form.submit class: "button is-primary"








= javascript_pack_tag 'calendar'
/ .datepicker#my-element

app/views/bookings/update.slim
.container
	h1 update attributes

	= form_with method: :patch, url: booking_path, model: @update do |f|
		= f.label :name, "Enter your name"
		= f.text_field :name, class: "input"
		= f.label :date, "Please select a date"
		= f.text_field :booking_from, class: "datepicker", type: "date", id: "datepicker"
		= f.label :phone, "Phone number"
		= f.text_field :phone, class: "input"
		= f.submit "update", class: "button is-primary"




= javascript_pack_tag 'calendar'

app/views/layouts/_footer.slim
.container.p-5
	= link_to "Contact us", contact_us_path
		

app/views/layouts/_header.slim
.navbar.is-transparent role="navigation" aria-label="main navigation"
	.container
		.navbar-brand
			.navbar-item.no-padding
				= link_to root_path do 
					= image_tag "logo.png", id: "navbar_logo"
			.navbar-burger role="button" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"
				span aria-hidden="true"
				span aria-hidden="true"
				span aria-hidden="true"
		.navbar-menu
			.navbar-start
				.navbar-item Home
				.navbar-item Documentation
				.navbar-item.has-dropdown.is-hoverable
					.navbar-link More
						
					
					.navbar-dropdown
							
						= link_to "About", about_path, class: "navbar-item"
							
						= link_to "Contact us", contact_us_path, class: "navbar-item"
							
						.navbar-divider
							- if user_signed_in?
								= link_to "new booking", new_booking_path, class: "navbar-item"
								- if current_user.bookings.any? 
									= link_to "change booking", bookings_path, class: "navbar-item"
			 
			- if user_signed_in? 
				.navbar-end
					.navbar-item
						.button.is-primari
							= link_to "log out", destroy_user_session_path, method: :delete, class: "link"
			- else
				.navbar-end
					.navbar-item
						.button.is-primari
							= link_to "Sign up", new_user_registration_path, class: "link"
					.navbar-item
						.button.is-light
							= link_to "Log in", new_user_session_path, class: "link"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evrepair</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/home.slim
h1 hdewuqh

app/views/static_pages/contact_us.slim
iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2450.0819179278515!2d20.951581315718748!3d52.11463827394306!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47193180738c2ac5%3A0x5a92efd7c584d676!2sZ%C5%82ota%2051%2C%2005-090%20Podolszyn%20Nowy!5e0!3m2!1sen!2spl!4v1613824018325!5m2!1sen!2spl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"

.button.is-primari
	a.link href="tel:+48605542453" Call us Today

app/views/static_pages/home.slim
.container
	.columns
		.column.is-8
			= image_tag "ev-hood", class: ""
		.column.is-4 
			ul.text1.p-5 Book an appointment today!
			.button.is-primari
				= link_to "Book now", new_booking_path, class: "link"
			
	.columns.p-5.is-centered
		.text1 What we offer
	.columns.p-5
		.column.is-4 
			li.text2.p-5  in-depth computer diagnostics
			li.text2.p-5  Mechanical repair and regular services
		.column.is-2
			.card#small_card
				.small_svg
					= image_tag "diagnostics.svg"
					.text2 Diagnostics
			.columns#spacer
			.card#small_card
				.svgcard
					= image_tag "mechanics.svg"
					.text2 Mechanics

		.column.is-2
			.card#small_card
				.small_svg
					= image_tag "reviews.svg"
					.text2 Reviews
			.columns#spacer
			.card#small_card
				.small_svg
					= image_tag "accesories.svg"
					.text2 Accessories
		.column.is-4
			li.text2.p-5 see our reviews from other customers
			li.text2.p-5 dealership for weird wires




.slideshow-container

	.myslides.fade
		.numbertext 1 / 4
		a href="https://liqui-moly.pl/"
			= image_tag "liquimoly1.jpg"
	.myslides.fade
		.numbertext 2 / 4
		a href="https://agdpro.pl/13-ladowanie-ev"
			= image_tag "weird-wires1.jpg"
	.myslides.fade
		.numbertext 3 / 4
		a href="https://liqui-moly.pl/"
			= image_tag "liquimoly2.jpg"
	.myslides.fade
		.numbertext 4 / 4
		a href="https://agdpro.pl/13-ladowanie-ev"
			= image_tag "weird-wires2.jpg"

	a.prev &#10094;
	a.next &#10095;

.dots style="text-align:center"
	span.dot onclick="currentSlide(1)"
	span.dot onclick="currentSlide(2)"
	span.dot onclick="currentSlide(3)"
	span.dot onclick="currentSlide(4)"


= javascript_pack_tag 'slideshow'